name: agenta-gh-ssl

services:
    web:
        profiles:
            - with-web

        build:
            context: ../../../web
            dockerfile: oss/docker/Dockerfile.gh

        networks:
            - agenta-gh-ssl-network
        labels:
            - "traefik.http.routers.web.rule=Host(`${TRAEFIK_DOMAIN}`) && PathPrefix(`/`)"
            - "traefik.http.routers.web.entrypoints=web,web-secure"
            - "traefik.http.services.web.loadbalancer.server.port=3000"
            - "traefik.http.routers.web.tls=true"
            - "traefik.http.routers.web.tls.certresolver=myResolver"
        env_file:
            - ${ENV_FILE:-./.env.oss.gh}
        command: sh -c "node ./oss/server.js"
        restart: always

    api:
        build: 
            context: ../../../api
            dockerfile: oss/docker/Dockerfile.gh

        volumes:
            - /var/run/docker.sock:/var/run/docker.sock

        networks:
            - agenta-gh-ssl-network
        extra_hosts:
            - "host.docker.internal:host-gateway"
        labels:
            - "traefik.http.routers.api.rule=Host(`${TRAEFIK_DOMAIN}`) && PathPrefix(`/api/`)"
            - "traefik.http.routers.api.entrypoints=web,web-secure"
            - "traefik.http.middlewares.api-strip.stripprefix.prefixes=/api"
            - "traefik.http.middlewares.api-strip.stripprefix.forceslash=true"
            - "traefik.http.routers.api.middlewares=api-strip"
            - "traefik.http.services.api.loadbalancer.server.port=8000"
            - "traefik.http.routers.api.service=api"
            - "traefik.http.routers.api.tls=true"
            - "traefik.http.routers.api.tls.certresolver=myResolver"
        env_file:
            - ${ENV_FILE:-./.env.oss.gh}
        command:
            [
                "newrelic-admin",
                "run-program",
                "uvicorn",
                "entrypoint:app",
                "--host",
                "0.0.0.0",
                "--port",
                "8000",
                "--reload",
                "--root-path",
                "/api"
            ]

        depends_on:
            postgres:
                condition: service_healthy
            alembic:
                condition: service_completed_successfully
        restart: always

    worker:
        build: 
            context: ../../../api
            dockerfile: oss/docker/Dockerfile.gh

        volumes:
            - /var/run/docker.sock:/var/run/docker.sock

        networks:
            - agenta-gh-ssl-network
        extra_hosts:
            - "host.docker.internal:host-gateway"
        env_file:
            - ${ENV_FILE:-./.env.oss.gh}

        command:
            [
                "newrelic-admin",
                "run-program",
                "celery",
                "-A",
                "entrypoint.celery_app",
                "worker",
                "--concurrency=1",
                "--max-tasks-per-child=1",
                "--prefetch-multiplier=1"
            ]
        depends_on:
            postgres:
                condition: service_healthy
            rabbitmq:
                condition: service_healthy
            redis:
                condition: service_healthy
        restart: always

    alembic:
        build: 
            context: ../../../api
            dockerfile: oss/docker/Dockerfile.gh

        volumes:
            - /var/run/docker.sock:/var/run/docker.sock

        networks:
            - agenta-gh-ssl-network
        env_file:
            - ${ENV_FILE:-./.env.oss.gh}

        command: sh -c "python -c 'from oss.databases.postgres.migrations.utils import split_core_and_tracing as split; split(); from oss.databases.postgres.migrations.core.utils import run_alembic_migration as run; run(); from oss.databases.postgres.migrations.tracing.utils import run_alembic_migration as run; run(); from oss.databases.postgres.migrations.utils import copy_nodes_from_core_to_tracing as copy; copy();'"
        depends_on:
            postgres:
                condition: service_healthy

    completion:
        build: 
            context: ../../../services/completion
            dockerfile: oss/docker/Dockerfile.gh

        volumes:
            - ../../../services/completion:/app
            - ../../../sdk:/sdk
        networks:
            - agenta-gh-ssl-network
        extra_hosts:
            - "host.docker.internal:host-gateway"
        labels:
            - "traefik.http.routers.completion.rule=Host(`${TRAEFIK_DOMAIN}`) && PathPrefix(`/services/completion/`)"
            - "traefik.http.routers.completion.entrypoints=web,web-secure"
            - "traefik.http.middlewares.completion-strip.stripprefix.prefixes=/services/completion"
            - "traefik.http.middlewares.completion-strip.stripprefix.forceslash=true"
            - "traefik.http.routers.completion.middlewares=completion-strip"
            - "traefik.http.services.completion.loadbalancer.server.port=80"
            - "traefik.http.routers.completion.service=completion"
            - "traefik.http.routers.completion.tls=true"
            - "traefik.http.routers.completion.tls.certresolver=myResolver"
        env_file:
            - ${ENV_FILE:-./.env.oss.gh}

        command: ["python", "oss/src/main.py"]
        restart: always

    chat:
        build:
            context: ../../../services/chat
            dockerfile: oss/docker/Dockerfile.gh
        volumes:
            - ../../../services/chat:/app
            - ../../../sdk:/sdk
        env_file:
            - ${ENV_FILE:-./.env.oss.gh}
        extra_hosts:
            - "host.docker.internal:host-gateway"
        labels:

            - "traefik.http.routers.chat.rule=Host(`${TRAEFIK_DOMAIN}`) && PathPrefix(`/services/chat/`)"
            - "traefik.http.routers.chat.entrypoints=web,web-secure"
            - "traefik.http.middlewares.chat-strip.stripprefix.prefixes=/services/chat"
            - "traefik.http.middlewares.chat-strip.stripprefix.forceslash=true"
            - "traefik.http.routers.chat.middlewares=chat-strip"
            - "traefik.http.services.chat.loadbalancer.server.port=80"
            - "traefik.http.routers.chat.service=chat"
            - "traefik.http.routers.chat.tls=true"
            - "traefik.http.routers.chat.tls.certresolver=myResolver"
        networks:
            - agenta-gh-ssl-network

        command: ["python", "oss/src/main.py"]
        restart: always

    postgres:
        image: postgres:16.2

        volumes:
            - postgres-data:/var/lib/postgresql/data/
            - ../../../api/oss/databases/postgres/init-db-oss.sql:/docker-entrypoint-initdb.d/init-db.sql

        restart: always
        networks:
            - agenta-gh-ssl-network
        env_file:
            - ${ENV_FILE:-./.env.oss.gh}
        ports:
            - "${POSTGRES_PORT:-5432}:5432"

        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 10s
            timeout: 5s
            retries: 5

    rabbitmq:
        image: rabbitmq:3-management

        volumes:
            - rabbitmq-data:/var/lib/rabbitmq

        networks:
            - agenta-gh-ssl-network
        env_file:
            - ${ENV_FILE:-./.env.oss.gh}

        ports:
            - "${RABBITMQ_PORT:-5672}:5672"
            - "${RABBITMQ_UI_PORT:-15672}:15672"
        restart: always
        healthcheck:
            test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
            interval: 10s
            timeout: 5s
            retries: 5

    redis:
        image: redis:latest
            
        volumes:
            - redis-data:/data

        networks:
            - agenta-gh-ssl-network

        restart: always
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 10s
            timeout: 5s
            retries: 5

    cache:
        image: redis:latest

        command: >
            redis-server
            --port 6378
            --appendonly no
            --appendfsync no
            --save ""
            --maxmemory 128mb
            --maxmemory-policy allkeys-lru

        ports:
            - "${REDIS_CACHE_PORT:-6378}:6378"

        volumes:
            - cache-data:/data

        networks:
            - agenta-gh-ssl-network

        labels:
            - "traefik.enable=false"

        restart: always

        healthcheck:
            test: ["CMD", "redis-cli", "-p", "6378", "ping"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 5s

    traefik:
        image: traefik:v2.10
        volumes:
            - ./ssl/traefik.yml:/traefik.yml
            - /var/run/docker.sock:/var/run/docker.sock
            - ${AGENTA_SSL_DIR:-/home/ubuntu/ssl_certificates}/acme.json:/acme.json
        networks:
            - agenta-gh-ssl-network
        ports:
            - "${TRAEFIK_PORT:-80}:${TRAEFIK_PORT:-80}"
            - "${TRAEFIK_UI_PORT:-8080}:8080"
            - "${TRAEFIK_HTTPS_PORT:-443}:${TRAEFIK_HTTPS_PORT:-443}"
        restart: always

    supertokens:
        image: registry.supertokens.io/supertokens/supertokens-postgresql

        depends_on:
            postgres:
                condition: service_healthy
        ports:
            - "${SUPERTOKENS_PORT:-3567}:3567"
        env_file:
            - ${ENV_FILE:-./.env.oss.gh}
        networks:
            - agenta-gh-ssl-network
        healthcheck:
            test: >
                bash -c 'exec 3<>/dev/tcp/127.0.0.1/3567 && echo -e "GET /hello HTTP/1.1\r\nhost: 127.0.0.1:3567\r\nConnection: close\r\n\r\n" >&3 && cat <&3 | grep "Hello"'
            interval: 10s
            timeout: 5s
            retries: 5
        restart: always

    hasura:
        image: hasura/graphql-engine:v2.44.0
        depends_on:
            postgres:
                condition: service_healthy
        ports:
            - "${HASURA_PORT:-8090}:8080"
        env_file:
            - ${ENV_FILE:-./.env.oss.gh}
        environment:
            ## Database URL for Hasura - connecting to agenta_oss_core as primary database
            HASURA_GRAPHQL_DATABASE_URL: postgresql://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@postgres:5432/agenta_oss_core
            
            ## Enable console (set to false in production)
            HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
            
            ## Enable dev mode (set to false in production)
            HASURA_GRAPHQL_DEV_MODE: "true"
            
            ## Admin secret for Hasura Console access
            HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_ADMIN_SECRET:-hasura_admin_secret}
            
            ## Enable the metadata database (uses the same DB as data)
            HASURA_GRAPHQL_METADATA_DATABASE_URL: postgresql://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@postgres:5432/agenta_oss_core
            
            ## Enable query logging
            HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
            
            ## Naming convention for auto-generated names
            HASURA_GRAPHQL_DEFAULT_NAMING_CONVENTION: hasura-default
            
        labels:
            - "traefik.http.routers.hasura.rule=PathPrefix(`/hasura`)"
            - "traefik.http.routers.hasura.entrypoints=web"
            - "traefik.http.middlewares.hasura-strip.stripprefix.prefixes=/hasura"
            - "traefik.http.routers.hasura.middlewares=hasura-strip"
            - "traefik.http.services.hasura.loadbalancer.server.port=8080"
            - "traefik.http.routers.hasura.service=hasura"
        networks:
            - agenta-gh-ssl-network
        restart: always
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8080/healthz"]
            interval: 30s
            timeout: 10s
            retries: 5
            start_period: 30s

networks:
    agenta-gh-ssl-network:

volumes:
    postgres-data:
    rabbitmq-data:
    redis-data:
    cache-data: